source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'page-object', '~> 2.0'
gem 'data_magic'
gem 'pry'
gem 'site_prism', '~> 3.7', '>= 3.7.3'
gem 'selenium-webdriver'
gem 'capybara'
gem 'allure-cucumber'
gem 'allure-rspec'
